Remove extra output for dbt2 clients from aws output
EnterpriseDB/postgres-deployment pull request #206
Opened 2021-07-28 22:30 UTC by mw2q

2021-08-12 08:28 UTC, jt-edb requested changes
The overall LGTM, but I think the refactoring part around _build_terraform_vars_file/_build_terraform_vars should be done via a dedicated PR. I agree with you, code factorisation would reduce the amount of duplicated code on this side and help us in terms of maintenance, but we need to cover all the cases and ensuring everything works as expected. Let's do this work in a dedicated PR. Thank you.

2021-08-23 15:48 UTC, mw2q commented
On Thu, Aug 12, 2021 at 01:28:40AM -0700, Julien Tachoires wrote:
> @jt-edb requested changes on this pull request.
> 
> The overall LGTM, but I think the refactoring part around _build_terraform_vars_file/_build_terraform_vars should be done via a dedicated PR. I agree with you, code factorisation would reduce the amount of duplicated code on this side and help us in terms of maintenance, but we need to cover all the cases and ensuring everything works as expected. Let's do this work in a dedicated PR. Thank you.

Ok, will do.

2021-08-30 23:36 UTC, mw2q commented
> The overall LGTM, but I think the refactoring part around _build_terraform_vars_file/_build_terraform_vars should be done via a dedicated PR. I agree with you, code factorisation would reduce the amount of duplicated code on this side and help us in terms of maintenance, but we need to cover all the cases and ensuring everything works as expected. Let's do this work in a dedicated PR. Thank you.

Pulled out into #226.

2021-09-27 11:38 UTC, jt-edb approved these changes

2021-09-27 11:38 UTC, merged