GCloud GKE support via Terraform and Ansible
EnterpriseDB/postgres-deployment pull request #335
Opened 2022-09-22 22:30 UTC by dougortiz

1. Support for GCloud GKE via Terraform
2. CloudNativePG deployment on GKE
3. CloudNative Postgres deployment on GKE
4. Terraform Version: 1.2.6
5. Ansible Version:  2.12.18
6. GCloud CLI - Version: 398.0.0

2022-10-05 17:28 UTC, bryan-bar requested changes
Hello @dougortiz
please review the following:

- Duplicate roles available under `edb-ansible` should be used for `cloudnativepostgres` and `cloudnativepg`
- 2 role directories with the same tasks: `edbdeploy/ansible/roles` and `edbdeploy/ansible/kubernetes-roles`. Are both needed?
- default `appid` and `password` is currently set for azure

2022-10-05 17:28 UTC, bryan-bar commented on edbdeploy/data/terraform/azure-aks/terraform.tfvars
> +password         = "MYI.D1KxtQrdBV01k2x4L.Vp13nLfGWlyg"
default password should be removed

2022-10-05 17:28 UTC, bryan-bar commented on edbdeploy/data/ansible/kubernetes_roles/remove_cloudnativepg_sandbox/README.md
> +# remove_cloudnativepg_sandbox
Duplicate role in edb-ansible:
https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/remove_cloudnativepg_sandbox

2022-10-05 17:28 UTC, bryan-bar commented on edbdeploy/data/ansible/kubernetes_roles/remove_cloudnativepostgres_sandbox/README.md
> +# remove_cloudnativepostgres_sandbox
Duplicate role in edb-ansible:
https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/remove_cloudnativepostgres_sandbox

2022-10-05 17:28 UTC, bryan-bar commented on edbdeploy/data/ansible/kubernetes_roles/setup_cloudnativepg_sandbox/README.md
> +# setup_cloudnativepg_sandbox
Duplicate role in edb-ansible:
https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/setup_cloudnativepg_sandbox

2022-10-05 17:28 UTC, bryan-bar commented on edbdeploy/data/ansible/kubernetes_roles/setup_cloudnativepostgres_sandbox/README.md
> +# setup_cloudnativepostgres_sandbox
Duplicate role in edb-ansible:
https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/setup_cloudnativepostgres_sandbox

2022-10-19 13:15 UTC, bryan-bar requested changes
Merge conflict in `edbdeploy/ansible.py`

2022-10-19 16:36 UTC, dougortiz commented
Request another review

2023-01-04 20:56 UTC, dougortiz commented
GKE refactoring of code

2023-01-04 21:05 UTC, dougortiz commented
GKE was refactored via PR: 335

2023-01-04 21:08 UTC, merged

2023-01-04 21:09 UTC, dougortiz commented
Squash and merged